name: 06-workflow-contexts
run-name: 06-workflow-contexts | DEBUG - ${{ inputs.debug }}
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        description: "Run the workflow in debug mode"
        type: boolean
        default: false

env:
  MY_VAR2: "workflow level variable value"

jobs:
  echo1:
    runs-on: ubuntu-latest
    env:
      MY_VAR2: "job-overriden variable value"
    steps:
      - name: Display Github meta data
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
      - name: Retrieve Variable Values
        env:
          MY_VAR2: "step-overriden variable value"
        run: |
          echo "MY_VAR: ${{ vars.MY_VAR }}"
          echo "MY_VAR2: ${{ env.MY_VAR2 }}"
  echo2:  
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Variable Values2
        run: |
          echo "Github Actions Repository Variable: MY_VAR: $MY_VAR"
          echo "MY_VAR2: $MY_VAR2"