name: 06-workflow-contexts

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      MY_VAR:
        description: 'Log level'
        required: true
        default: 'hello world'
        type: choice
        options:
        - hello world 
        - info
        - warning
        - debug


jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Display Info
        run: |
          "Event name: ${{ github.event_name }}"

          "Ref: ${{ github.ref }}"

          "SHA: ${{ github.sha }}"

          "Actor: ${{ github.actor }}"

          "Workflow: ${{ github.workflow }}"

          "Run ID: ${{ github.run_id }}"

          "Run number: ${{ github.run_number }}"
      - name: Retrieve Variable
        run: |
          echo "MY_VAR: $MY_VAR" 