name: 10 - Execution flow
on:
  workflow_dispatch:
    inputs: 
      pass-unit-tests:
        description: "Pass unit tests"
        type: boolean
        default: "false"


jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: "Lint and build..."
        run: echo "Linting and building..."
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Run unit tests..."
        run: echo "Running tests..."
      - name: "Failing tests..."
        if: ${{ !inputs.pass-unit-tests }}
        run: exit 1
  deploy-nonprod:
    runs-on: ubuntu-latest
    needs:
      - lint-build
      - unit-tests
    steps:
      - name: Deploying to non-prod
        run: echo "Deploying to non-prod..."
  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: Run E2E tests
        run: echo "Running E2E tests..."
  load-tests:
      runs-on: ubuntu-latest
      needs: deploy-nonprod
      steps:
        - name: Run Load tests
          run: echo "Running Load tests..."
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to prod
        run: echo "Deploying to prod..."

