name: 12 - Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        description: 'Build Status'
        required: true
        default: 'success'
        type: choice
        options:
          - success
          - failure

  

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_OUTPUT
      - name: Build
        id: build
        run: |
          echo "status=${{  inputs.build-status }}" >> "$GITHUB_OUTPUT"
      - name: Print outputs
        run: echo "${{ steps.build.outputs.status }}"
  deploy:
    runs-on: ubuntu-latest
    name: Print build status
    needs: build
    if: "${{ needs.build.outputs.status == 'success' }}"
    steps:
      - name: Deploy
        run: echo "Deploying.."