name: 15 - Working w/ M3x

on:
  workflow_dispatch:

jobs:
  backwards-compat:
    name: ${{matrix.os}} - Node ${{matrix.node-version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [ 18.x, 21.x ]
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Hello World
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Perform tests
        run: echo "Hello World"
  