name: 15 - Working w/ M3x

on:
  workflow_dispatch:

jobs:
  backwards-compat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Hello World
        uses: actions/setup-node@v3
        with: ${{ matrix.node-version }}
      - name: Perform tests
        run: echo "Hello World"
  