name: 15 - Working w/ M3x

on:
  workflow_dispatch:

jobs:
  backwards-compat:
    name: ${{matrix.os}} - Node ${{matrix.node-version}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 21.x]
        os: [ubuntu-latest, windows-latest]
        include: # allows adding specific combinations to the matrix
          - node-version: 18.x
            os: windows-latest
          - node-version: 21.x # add tags to a specific combo
            os: ubuntu-latest
            tag: experimental
    steps:
      - name: Hello World
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fail if experimental
        if: ${{ matrix.tag == 'experimental' }}
        run: exit 1
      - name: Perform tests
        run: echo "Hello World"

  include-experiment:
    name: ${{matrix.color}} - ${{matrix.shape}} - ${{matrix.size}}
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: false
      matrix:
        color: [red, green]
        shape: [circle, square]
        size: [small, large]
        include:
          - color: yellow
            shape: triangle
            opacity: 100
          - shape: circle
            opacity: 75
          - color: blue
            shape: square
          - opacity: 50 # latest opacity key in the array overrides the previous ones (100,& 75) and adds to the orig ma3x
    steps:
      - name: Hello World
        run: echo "${{matrix.color}} - ${{matrix.shape}} - ${{matrix.size}}"