name: 19.2 - Reusable-workflow

on:
  workflow_dispatch:

jobs:
  deploy-app:
    uses: ./.github/workflows/19.1-reusable-workflow
    with:
      target-dir: dummy-dir
  deploy-outputs:
    runs-on: ubuntu-latest
    needs: deploy-app
    steps:
      - name: Print outputs
        run: |
          echo "Build status: ${{ needs.deploy.outputs.build-status }}"
          echo "App deployed version URL: ${{ needs.deploy.outputs.url }}"
