name: 29 - Concurrency

on:
  workflow_dispatch:

concurrency: 
# best to bound single concurrency group to a single workflow
# multiple workflows with the same concurrency group could lead to weird behavior
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        id: ping-url
        with:
          url: https://www.google.com
          max_trials: 10
          delay: 5