name: 21 - Workflow security

on:
  pull_request:

jobs:
  insec-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check PR title
        run: |
          title=${{ github.event.pull_request.title }}
          if [[ $title =~ ^feat ]]; then
          echo "PR is a feature"
          exit 0
          else
          echo "PR is not a feature"
          exit 1
          fi
  safer-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          title=${{ github.event.pull_request.title }}
          if [[ $title =~ ^feat ]]; then
          echo "PR is a feature"
          exit 0
          else
          echo "PR is not a feature"
          exit 1
          fi